services:  
  nfsserver:
    image: truongvanhuy2000/nfsservertest
    container_name: nfsserver
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data/resources
    volumes:
      - video:/data/resources
    networks:
      - vanhuy
    
  nfsclient:
    image: truongvanhuy2000/nfsclienttest
    container_name: nfsclient
    privileged: true
    env_file:
      - client.env
    depends_on:
      - nfsserver
    networks:
      - vanhuy
volumes:
  video:

networks:
  vanhuy:
    ipam:
      driver: default
