services:  
  nfsserver:
    image: truongvanhuy2000/nfsservertest
    # build: nfsserver
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data/resources
    volumes:
      - video:/data/resources
    networks:
      - vanhuy
    
  nfsclient:
    image: truongvanhuy2000/nfsclienttest
    # build: nfsclient
    privileged: true
    env_file:
      - client.env
    depends_on:
      - nfsserver
    networks:
      - vanhuy
    volumes:
      - "video:/video/"

volumes:
  video:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfsserver,nolock,soft,rw
      device: ":/data/resources"

networks:
  vanhuy:
    ipam:
      driver: default
